spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: via-cep
          uri: lb://viacep
          predicates:
            - Path=/address/**

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka/